name: Release
on:
  workflow_dispatch:
  push:
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Get environment variables for later
      - uses: FranzDiebold/github-env-vars-action@v2
      
      - uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config --global user.email "ryan@nutt.com"
          git config --global user.name "Ryan Nutt"
      - name: Run build
        run: |
          npm install --silent
          npm run build
          git add dist/
          git commit -m "Releasing" --allow-empty
          git push -f origin ${{ env.CI_REF_NAME }}
      - name: Get version
        id: project-version
        uses: "euberdeveloper/ga-project-version@main"
        with:
          package-manager: npm
      - name: Create release
        run: |
          gh release delete ${{ env.CI_REF_NAME }} -y || echo "No release to delete"
          gh release create ${{ env.CI_REF_NAME }} -t ${{ env.CI_REF_NAME }} -n "Release ${{ env.CI_REF_NAME }}"
        env:
          GH_TOKEN: ${{ github.token }}

